### ISSUE TITLE
[Question] Source of vectors?

### ISSUE THREAD

**Issue by mreishus** [turbomaze/word2vecjson#1]
Thanks for this project.   It's interesting to see it all done in javascript.  I'm just curious, what is the source of the vectors you have included here?  Did you generate them yourself of use a truncated version of a famous source like `GoogleNews-vectors-negative300.bin.gz`?

**Comment by turbomaze** [comment]
Yup! You're right. I suppose I should make this clearer in the readme, but
the vectors come from the first link I shared, the version you mentioned.

**Comment by mreishus** [comment]
Ok, thanks!

**Comment by kostasx** [comment]
Shit! Seems like patriarchy is baked into the vectors' source...

Similar vectors to 'woman':
woman	1
man	0.7664011739467016
girl	0.7494646687908358
...
housewife 0.5463817659534669
victim	0.5450068478979083 

:(
